# Generated by Django 5.0 on 2024-01-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timestamp',
                 models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
