# Generated by Django 5.0 on 2023-12-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('statuses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name', models.CharField(max_length=200)
                ),
                (
                    'description', models.CharField(max_length=200)
                ),
                (
                    'timestamp',
                    models.DateTimeField(auto_now_add=True)
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='author',
                        to='users.profile'
                    )
                ),
                (
                    'label',
                    models.ManyToManyField(blank=True, to='labels.label')
                ),
                (
                    'responsible',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='responsible',
                        to='users.profile'
                    )
                ),
                (
                    'status', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statuses.status'
                    )
                ),
            ],
        ),
    ]
