# Generated by Django 5.0 on 2023-12-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_label_task_labels_alter_task_author_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='executor', to='users.profile', verbose_name='Исполнитель'),
            preserve_default=False,
        ),
    ]
